from __future__ import annotations

from dataclasses import asdict, is_dataclass
from pathlib import Path

import yaml

from pipeline.detections.sigma_rule import SigmaRule


class SigmaExporter:
    """
    Exports Sigma rules as a YAML document.

    The exporter performs no detection logic. It simply serializes
    SigmaRule objects generated by SigmaBuilder.
    """

    def export(
        self,
        destination: Path,
        rules: list[SigmaRule],
    ) -> None:

        destination.parent.mkdir(
            parents=True,
            exist_ok=True,
        )

        documents: list[dict] = []

        for rule in rules:
            if is_dataclass(rule):
                documents.append(
                    asdict(rule),
                )
            else:
                documents.append(
                    rule.model_dump(),
                )

        with destination.open(
            "w",
            encoding="utf-8",
        ) as output:
            yaml.safe_dump_all(
                documents,
                output,
                sort_keys=False,
                allow_unicode=True,
            )
